            #form_login: ~
security:
    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        SONATA:
            - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    providers:
        fos_userbundle:
        # à désactiver quand tout est Ok
            # id: fos_user.user_provider.email
            id: fos_user.user_provider.username_email
        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
#            remember_me:
#                secret: ''
#                lifetime: 1000
#                path: /
            pattern: ^/
            context: user
            form_login:
                provider: fos_userbundle
#                csrf_token_generator: security.csrf.token_manager
                login_path: /login
                use_forward: false
                use_referer: true
                check_path: /login_check
                default_target_path: /
#                failure_path:   null
            logout:
              path: /logout
              target: /login
            anonymous:  true
#            logout_on_user_change: true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

